module.exports = [
"[next]/internal/font/google/inter_5972bc34.module.css [app-rsc] (css module)", ((__turbopack_context__) => {

__turbopack_context__.v({
  "className": "inter_5972bc34-module__OU16Qa__className",
});
}),
"[next]/internal/font/google/inter_5972bc34.js [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$inter_5972bc34$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__ = __turbopack_context__.i("[next]/internal/font/google/inter_5972bc34.module.css [app-rsc] (css module)");
;
const fontData = {
    className: __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$inter_5972bc34$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].className,
    style: {
        fontFamily: "'Inter', 'Inter Fallback'",
        fontStyle: "normal"
    }
};
if (__TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$inter_5972bc34$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].variable != null) {
    fontData.variable = __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$inter_5972bc34$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].variable;
}
const __TURBOPACK__default__export__ = fontData;
}),
"[externals]/node:crypto [external] (node:crypto, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("node:crypto", () => require("node:crypto"));

module.exports = mod;
}),
"[externals]/node:fs [external] (node:fs, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("node:fs", () => require("node:fs"));

module.exports = mod;
}),
"[externals]/node:path [external] (node:path, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("node:path", () => require("node:path"));

module.exports = mod;
}),
"[project]/components/common/header.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/components/common/header.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/common/header.tsx <module evaluation>", "default");
}),
"[project]/components/common/header.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/components/common/header.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/common/header.tsx", "default");
}),
"[project]/components/common/header.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$common$2f$header$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/components/common/header.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$common$2f$header$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/components/common/header.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$common$2f$header$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/components/common/site-footer.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>SiteFooter
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$app$2d$dir$2f$link$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/client/app-dir/link.react-server.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$lucide$2d$react$2f$dist$2f$esm$2f$icons$2f$brain$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__default__as__Brain$3e$__ = __turbopack_context__.i("[project]/node_modules/lucide-react/dist/esm/icons/brain.js [app-rsc] (ecmascript) <export default as Brain>");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$lucide$2d$react$2f$dist$2f$esm$2f$icons$2f$github$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__default__as__Github$3e$__ = __turbopack_context__.i("[project]/node_modules/lucide-react/dist/esm/icons/github.js [app-rsc] (ecmascript) <export default as Github>");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$lucide$2d$react$2f$dist$2f$esm$2f$icons$2f$twitter$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__default__as__Twitter$3e$__ = __turbopack_context__.i("[project]/node_modules/lucide-react/dist/esm/icons/twitter.js [app-rsc] (ecmascript) <export default as Twitter>");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$lucide$2d$react$2f$dist$2f$esm$2f$icons$2f$mail$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__default__as__Mail$3e$__ = __turbopack_context__.i("[project]/node_modules/lucide-react/dist/esm/icons/mail.js [app-rsc] (ecmascript) <export default as Mail>");
;
;
;
function SiteFooter() {
    const currentYear = new Date().getFullYear();
    const footerLinks = {
        Product: [
            {
                label: "Features",
                href: "/#features"
            },
            {
                label: "How It Works",
                href: "/#how-it-works"
            },
            {
                label: "Workspaces",
                href: "/select-org"
            }
        ],
        Access: [
            {
                label: "Sign In",
                href: "/sign-in"
            },
            {
                label: "Sign Up",
                href: "/sign-up"
            },
            {
                label: "Select Org",
                href: "/select-org"
            }
        ],
        Workspace: [
            {
                label: "Dashboard",
                href: "/select-org"
            },
            {
                label: "Documents",
                href: "/select-org"
            },
            {
                label: "Upload",
                href: "/select-org"
            }
        ],
        Support: [
            {
                label: "Create Workspace",
                href: "/sign-up"
            },
            {
                label: "Switch Organization",
                href: "/select-org"
            },
            {
                label: "Contact Us",
                href: "mailto:support@lumina-hq.com"
            }
        ]
    };
    const socialLinks = [
        {
            icon: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$lucide$2d$react$2f$dist$2f$esm$2f$icons$2f$github$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__default__as__Github$3e$__["Github"], {
                className: "h-5 w-5"
            }, void 0, false, {
                fileName: "[project]/components/common/site-footer.tsx",
                lineNumber: 32,
                columnNumber: 13
            }, this),
            href: "https://github.com",
            label: "GitHub"
        },
        {
            icon: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$lucide$2d$react$2f$dist$2f$esm$2f$icons$2f$twitter$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__default__as__Twitter$3e$__["Twitter"], {
                className: "h-5 w-5"
            }, void 0, false, {
                fileName: "[project]/components/common/site-footer.tsx",
                lineNumber: 37,
                columnNumber: 13
            }, this),
            href: "https://twitter.com",
            label: "Twitter"
        },
        {
            icon: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$lucide$2d$react$2f$dist$2f$esm$2f$icons$2f$mail$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__default__as__Mail$3e$__["Mail"], {
                className: "h-5 w-5"
            }, void 0, false, {
                fileName: "[project]/components/common/site-footer.tsx",
                lineNumber: 42,
                columnNumber: 13
            }, this),
            href: "mailto:support@lumina-hq.com",
            label: "Email"
        }
    ];
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("footer", {
        className: "border-t bg-gray-50",
        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
            className: "container mx-auto px-4 py-12",
            children: [
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                    className: "grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-5",
                    children: [
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                            className: "lg:col-span-2",
                            children: [
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                    className: "mb-4 flex items-center gap-2",
                                    children: [
                                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$lucide$2d$react$2f$dist$2f$esm$2f$icons$2f$brain$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$export__default__as__Brain$3e$__["Brain"], {
                                            className: "h-8 w-8 text-blue-600"
                                        }, void 0, false, {
                                            fileName: "[project]/components/common/site-footer.tsx",
                                            lineNumber: 54,
                                            columnNumber: 15
                                        }, this),
                                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {
                                            className: "text-xl font-bold",
                                            children: "Lumina-HQ"
                                        }, void 0, false, {
                                            fileName: "[project]/components/common/site-footer.tsx",
                                            lineNumber: 55,
                                            columnNumber: 15
                                        }, this)
                                    ]
                                }, void 0, true, {
                                    fileName: "[project]/components/common/site-footer.tsx",
                                    lineNumber: 53,
                                    columnNumber: 13
                                }, this),
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                    className: "mb-6 max-w-md text-gray-600",
                                    children: "AI-powered document analysis for teams. Upload, analyze, and collaborate on documents inside isolated organization workspaces."
                                }, void 0, false, {
                                    fileName: "[project]/components/common/site-footer.tsx",
                                    lineNumber: 57,
                                    columnNumber: 13
                                }, this),
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                    className: "flex gap-4",
                                    children: socialLinks.map((link)=>/*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("a", {
                                            href: link.href,
                                            target: "_blank",
                                            rel: "noopener noreferrer",
                                            className: "text-gray-400 transition-colors hover:text-gray-600",
                                            "aria-label": link.label,
                                            children: link.icon
                                        }, link.label, false, {
                                            fileName: "[project]/components/common/site-footer.tsx",
                                            lineNumber: 63,
                                            columnNumber: 17
                                        }, this))
                                }, void 0, false, {
                                    fileName: "[project]/components/common/site-footer.tsx",
                                    lineNumber: 61,
                                    columnNumber: 13
                                }, this)
                            ]
                        }, void 0, true, {
                            fileName: "[project]/components/common/site-footer.tsx",
                            lineNumber: 52,
                            columnNumber: 11
                        }, this),
                        Object.entries(footerLinks).map(([category, links])=>/*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                children: [
                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h3", {
                                        className: "mb-4 text-lg font-semibold",
                                        children: category
                                    }, void 0, false, {
                                        fileName: "[project]/components/common/site-footer.tsx",
                                        lineNumber: 79,
                                        columnNumber: 15
                                    }, this),
                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("ul", {
                                        className: "space-y-2",
                                        children: links.map((link)=>/*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("li", {
                                                children: link.href.startsWith("mailto:") ? /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("a", {
                                                    href: link.href,
                                                    className: "text-gray-600 transition-colors hover:text-gray-900",
                                                    children: link.label
                                                }, void 0, false, {
                                                    fileName: "[project]/components/common/site-footer.tsx",
                                                    lineNumber: 84,
                                                    columnNumber: 23
                                                }, this) : /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$app$2d$dir$2f$link$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
                                                    href: link.href,
                                                    className: "text-gray-600 transition-colors hover:text-gray-900",
                                                    children: link.label
                                                }, void 0, false, {
                                                    fileName: "[project]/components/common/site-footer.tsx",
                                                    lineNumber: 91,
                                                    columnNumber: 23
                                                }, this)
                                            }, link.label, false, {
                                                fileName: "[project]/components/common/site-footer.tsx",
                                                lineNumber: 82,
                                                columnNumber: 19
                                            }, this))
                                    }, void 0, false, {
                                        fileName: "[project]/components/common/site-footer.tsx",
                                        lineNumber: 80,
                                        columnNumber: 15
                                    }, this)
                                ]
                            }, category, true, {
                                fileName: "[project]/components/common/site-footer.tsx",
                                lineNumber: 78,
                                columnNumber: 13
                            }, this))
                    ]
                }, void 0, true, {
                    fileName: "[project]/components/common/site-footer.tsx",
                    lineNumber: 51,
                    columnNumber: 9
                }, this),
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                    className: "mt-8 flex flex-col items-center justify-between border-t pt-8 md:flex-row",
                    children: [
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                            className: "mb-4 text-gray-600 md:mb-0",
                            children: [
                                "© ",
                                currentYear,
                                " Lumina-HQ. All rights reserved."
                            ]
                        }, void 0, true, {
                            fileName: "[project]/components/common/site-footer.tsx",
                            lineNumber: 106,
                            columnNumber: 11
                        }, this),
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                            className: "flex gap-6 text-sm text-gray-600",
                            children: [
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$app$2d$dir$2f$link$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
                                    href: "/sign-in",
                                    className: "hover:text-gray-900",
                                    children: "Sign In"
                                }, void 0, false, {
                                    fileName: "[project]/components/common/site-footer.tsx",
                                    lineNumber: 110,
                                    columnNumber: 13
                                }, this),
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$app$2d$dir$2f$link$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
                                    href: "/sign-up",
                                    className: "hover:text-gray-900",
                                    children: "Sign Up"
                                }, void 0, false, {
                                    fileName: "[project]/components/common/site-footer.tsx",
                                    lineNumber: 113,
                                    columnNumber: 13
                                }, this),
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$app$2d$dir$2f$link$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
                                    href: "/select-org",
                                    className: "hover:text-gray-900",
                                    children: "Workspaces"
                                }, void 0, false, {
                                    fileName: "[project]/components/common/site-footer.tsx",
                                    lineNumber: 116,
                                    columnNumber: 13
                                }, this)
                            ]
                        }, void 0, true, {
                            fileName: "[project]/components/common/site-footer.tsx",
                            lineNumber: 109,
                            columnNumber: 11
                        }, this)
                    ]
                }, void 0, true, {
                    fileName: "[project]/components/common/site-footer.tsx",
                    lineNumber: 105,
                    columnNumber: 9
                }, this)
            ]
        }, void 0, true, {
            fileName: "[project]/components/common/site-footer.tsx",
            lineNumber: 50,
            columnNumber: 7
        }, this)
    }, void 0, false, {
        fileName: "[project]/components/common/site-footer.tsx",
        lineNumber: 49,
        columnNumber: 5
    }, this);
}
}),
"[externals]/node:async_hooks [external] (node:async_hooks, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("node:async_hooks", () => require("node:async_hooks"));

module.exports = mod;
}),
"[externals]/fs [external] (fs, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("fs", () => require("fs"));

module.exports = mod;
}),
"[externals]/os [external] (os, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("os", () => require("os"));

module.exports = mod;
}),
"[externals]/crypto [external] (crypto, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("crypto", () => require("crypto"));

module.exports = mod;
}),
"[externals]/node:url [external] (node:url, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("node:url", () => require("node:url"));

module.exports = mod;
}),
"[project]/generated/prisma/internal/class.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "getPrismaClientClass",
    ()=>getPrismaClientClass
]);
/* !!! This is code generated by Prisma. Do not edit directly. !!! */ /* eslint-disable */ // biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * Please import the `PrismaClient` class from the `client.ts` file instead.
 */ var __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__ = __turbopack_context__.i("[externals]/@prisma/client/runtime/client [external] (@prisma/client/runtime/client, cjs, [project]/node_modules/@prisma/client)");
;
const config = {
    "previewFeatures": [],
    "clientVersion": "7.5.0",
    "engineVersion": "280c870be64f457428992c43c1f6d557fab6e29e",
    "activeProvider": "postgresql",
    "inlineSchema": "// prisma/schema.prisma\n// Define your database models\n\ngenerator client {\n  provider = \"prisma-client\"\n  output   = \"../generated/prisma\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n}\n\nmodel Organization {\n  id         String               @id @default(cuid())\n  clerkOrgId String               @unique\n  name       String\n  slug       String               @unique\n  createdAt  DateTime             @default(now())\n  members    OrganizationMember[]\n  documents  Document[]\n\n  @@map(\"organizations\")\n}\n\nmodel OrganizationMember {\n  id             String       @id @default(cuid())\n  organizationId String\n  userId         String\n  role           String       @default(\"member\")\n  organization   Organization @relation(fields: [organizationId], references: [id])\n  user           User         @relation(fields: [userId], references: [id])\n\n  @@unique([organizationId, userId])\n  @@map(\"organization_members\")\n}\n\nmodel User {\n  id          String               @id @default(cuid())\n  clerkUserId String               @unique\n  email       String\n  name        String? // ? = optional\n  createdAt   DateTime             @default(now())\n  memberships OrganizationMember[]\n  documents   Document[]\n\n  @@map(\"users\")\n}\n\nmodel Document {\n  id             String       @id @default(cuid())\n  name           String\n  content        String?\n  fileUrl        String?\n  fileSize       Int?\n  fileType       String?\n  aiSummary      String?\n  aiKeywords     String[]\n  sentiment      String?\n  organizationId String\n  userId         String\n  organization   Organization @relation(fields: [organizationId], references: [id])\n  user           User         @relation(fields: [userId], references: [id])\n\n  createdAt DateTime @default(now())\n\n  @@map(\"documents\")\n}\n",
    "runtimeDataModel": {
        "models": {},
        "enums": {},
        "types": {}
    },
    "parameterizationSchema": {
        "strings": [],
        "graph": ""
    }
};
config.runtimeDataModel = JSON.parse("{\"models\":{\"Organization\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"clerkOrgId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"name\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"slug\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"createdAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"members\",\"kind\":\"object\",\"type\":\"OrganizationMember\",\"relationName\":\"OrganizationToOrganizationMember\"},{\"name\":\"documents\",\"kind\":\"object\",\"type\":\"Document\",\"relationName\":\"DocumentToOrganization\"}],\"dbName\":\"organizations\"},\"OrganizationMember\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"organizationId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"userId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"role\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"organization\",\"kind\":\"object\",\"type\":\"Organization\",\"relationName\":\"OrganizationToOrganizationMember\"},{\"name\":\"user\",\"kind\":\"object\",\"type\":\"User\",\"relationName\":\"OrganizationMemberToUser\"}],\"dbName\":\"organization_members\"},\"User\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"clerkUserId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"email\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"name\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"createdAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"memberships\",\"kind\":\"object\",\"type\":\"OrganizationMember\",\"relationName\":\"OrganizationMemberToUser\"},{\"name\":\"documents\",\"kind\":\"object\",\"type\":\"Document\",\"relationName\":\"DocumentToUser\"}],\"dbName\":\"users\"},\"Document\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"name\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"content\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"fileUrl\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"fileSize\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"fileType\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"aiSummary\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"aiKeywords\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"sentiment\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"organizationId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"userId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"organization\",\"kind\":\"object\",\"type\":\"Organization\",\"relationName\":\"DocumentToOrganization\"},{\"name\":\"user\",\"kind\":\"object\",\"type\":\"User\",\"relationName\":\"DocumentToUser\"},{\"name\":\"createdAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"}],\"dbName\":\"documents\"}},\"enums\":{},\"types\":{}}");
config.parameterizationSchema = {
    strings: JSON.parse("[\"where\",\"orderBy\",\"cursor\",\"organization\",\"memberships\",\"user\",\"documents\",\"_count\",\"members\",\"Organization.findUnique\",\"Organization.findUniqueOrThrow\",\"Organization.findFirst\",\"Organization.findFirstOrThrow\",\"Organization.findMany\",\"data\",\"Organization.createOne\",\"Organization.createMany\",\"Organization.createManyAndReturn\",\"Organization.updateOne\",\"Organization.updateMany\",\"Organization.updateManyAndReturn\",\"create\",\"update\",\"Organization.upsertOne\",\"Organization.deleteOne\",\"Organization.deleteMany\",\"having\",\"_min\",\"_max\",\"Organization.groupBy\",\"Organization.aggregate\",\"OrganizationMember.findUnique\",\"OrganizationMember.findUniqueOrThrow\",\"OrganizationMember.findFirst\",\"OrganizationMember.findFirstOrThrow\",\"OrganizationMember.findMany\",\"OrganizationMember.createOne\",\"OrganizationMember.createMany\",\"OrganizationMember.createManyAndReturn\",\"OrganizationMember.updateOne\",\"OrganizationMember.updateMany\",\"OrganizationMember.updateManyAndReturn\",\"OrganizationMember.upsertOne\",\"OrganizationMember.deleteOne\",\"OrganizationMember.deleteMany\",\"OrganizationMember.groupBy\",\"OrganizationMember.aggregate\",\"User.findUnique\",\"User.findUniqueOrThrow\",\"User.findFirst\",\"User.findFirstOrThrow\",\"User.findMany\",\"User.createOne\",\"User.createMany\",\"User.createManyAndReturn\",\"User.updateOne\",\"User.updateMany\",\"User.updateManyAndReturn\",\"User.upsertOne\",\"User.deleteOne\",\"User.deleteMany\",\"User.groupBy\",\"User.aggregate\",\"Document.findUnique\",\"Document.findUniqueOrThrow\",\"Document.findFirst\",\"Document.findFirstOrThrow\",\"Document.findMany\",\"Document.createOne\",\"Document.createMany\",\"Document.createManyAndReturn\",\"Document.updateOne\",\"Document.updateMany\",\"Document.updateManyAndReturn\",\"Document.upsertOne\",\"Document.deleteOne\",\"Document.deleteMany\",\"_avg\",\"_sum\",\"Document.groupBy\",\"Document.aggregate\",\"AND\",\"OR\",\"NOT\",\"id\",\"name\",\"content\",\"fileUrl\",\"fileSize\",\"fileType\",\"aiSummary\",\"aiKeywords\",\"sentiment\",\"organizationId\",\"userId\",\"createdAt\",\"equals\",\"in\",\"notIn\",\"lt\",\"lte\",\"gt\",\"gte\",\"not\",\"has\",\"hasEvery\",\"hasSome\",\"contains\",\"startsWith\",\"endsWith\",\"clerkUserId\",\"email\",\"every\",\"some\",\"none\",\"role\",\"clerkOrgId\",\"slug\",\"organizationId_userId\",\"is\",\"isNot\",\"connectOrCreate\",\"upsert\",\"createMany\",\"set\",\"disconnect\",\"delete\",\"connect\",\"updateMany\",\"deleteMany\",\"push\",\"increment\",\"decrement\",\"multiply\",\"divide\"]"),
    graph: "9wElQAoGAACDAQAgCAAAggEAIFEAAIYBADBSAAASABBTAACGAQAwVAEAAAABVQEAfwAhX0AAgQEAIXQBAAAAAXUBAAAAAQEAAAABACAJAwAAiQEAIAUAAIoBACBRAACMAQAwUgAAAwAQUwAAjAEAMFQBAH8AIV0BAH8AIV4BAH8AIXMBAH8AIQIDAADeAQAgBQAA3wEAIAoDAACJAQAgBQAAigEAIFEAAIwBADBSAAADABBTAACMAQAwVAEAAAABXQEAfwAhXgEAfwAhcwEAfwAhdgAAiwEAIAMAAAADACABAAAEADACAAAFACADAAAAAwAgAQAABAAwAgAABQAgEQMAAIkBACAFAACKAQAgUQAAhwEAMFIAAAgAEFMAAIcBADBUAQB_ACFVAQB_ACFWAQCAAQAhVwEAgAEAIVgCAIgBACFZAQCAAQAhWgEAgAEAIVsAAHEAIFwBAIABACFdAQB_ACFeAQB_ACFfQACBAQAhCAMAAN4BACAFAADfAQAgVgAAjQEAIFcAAI0BACBYAACNAQAgWQAAjQEAIFoAAI0BACBcAACNAQAgEQMAAIkBACAFAACKAQAgUQAAhwEAMFIAAAgAEFMAAIcBADBUAQAAAAFVAQB_ACFWAQCAAQAhVwEAgAEAIVgCAIgBACFZAQCAAQAhWgEAgAEAIVsAAHEAIFwBAIABACFdAQB_ACFeAQB_ACFfQACBAQAhAwAAAAgAIAEAAAkAMAIAAAoAIAEAAAADACABAAAACAAgAwAAAAgAIAEAAAkAMAIAAAoAIAEAAAADACABAAAACAAgAQAAAAEAIAoGAACDAQAgCAAAggEAIFEAAIYBADBSAAASABBTAACGAQAwVAEAfwAhVQEAfwAhX0AAgQEAIXQBAH8AIXUBAH8AIQIGAAC_AQAgCAAAvgEAIAMAAAASACABAAATADACAAABACADAAAAEgAgAQAAEwAwAgAAAQAgAwAAABIAIAEAABMAMAIAAAEAIAcGAADdAQAgCAAA3AEAIFQBAAAAAVUBAAAAAV9AAAAAAXQBAAAAAXUBAAAAAQEOAAAXACAFVAEAAAABVQEAAAABX0AAAAABdAEAAAABdQEAAAABAQ4AABkAMAEOAAAZADAHBgAAyQEAIAgAAMgBACBUAQCTAQAhVQEAkwEAIV9AAJcBACF0AQCTAQAhdQEAkwEAIQIAAAABACAOAAAcACAFVAEAkwEAIVUBAJMBACFfQACXAQAhdAEAkwEAIXUBAJMBACECAAAAEgAgDgAAHgAgAgAAABIAIA4AAB4AIAMAAAABACAVAAAXACAWAAAcACABAAAAAQAgAQAAABIAIAMHAADFAQAgGwAAxwEAIBwAAMYBACAIUQAAhQEAMFIAACUAEFMAAIUBADBUAQBuACFVAQBuACFfQAByACF0AQBuACF1AQBuACEDAAAAEgAgAQAAJAAwGgAAJQAgAwAAABIAIAEAABMAMAIAAAEAIAEAAAAFACABAAAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAMAAAADACABAAAEADACAAAFACADAAAAAwAgAQAABAAwAgAABQAgBgMAALsBACAFAADEAQAgVAEAAAABXQEAAAABXgEAAAABcwEAAAABAQ4AAC0AIARUAQAAAAFdAQAAAAFeAQAAAAFzAQAAAAEBDgAALwAwAQ4AAC8AMAYDAAC5AQAgBQAAwwEAIFQBAJMBACFdAQCTAQAhXgEAkwEAIXMBAJMBACECAAAABQAgDgAAMgAgBFQBAJMBACFdAQCTAQAhXgEAkwEAIXMBAJMBACECAAAAAwAgDgAANAAgAgAAAAMAIA4AADQAIAMAAAAFACAVAAAtACAWAAAyACABAAAABQAgAQAAAAMAIAMHAADAAQAgGwAAwgEAIBwAAMEBACAHUQAAhAEAMFIAADsAEFMAAIQBADBUAQBuACFdAQBuACFeAQBuACFzAQBuACEDAAAAAwAgAQAAOgAwGgAAOwAgAwAAAAMAIAEAAAQAMAIAAAUAIAoEAACCAQAgBgAAgwEAIFEAAH4AMFIAAEEAEFMAAH4AMFQBAAAAAVUBAIABACFfQACBAQAhbgEAAAABbwEAfwAhAQAAAD4AIAEAAAA-ACAKBAAAggEAIAYAAIMBACBRAAB-ADBSAABBABBTAAB-ADBUAQB_ACFVAQCAAQAhX0AAgQEAIW4BAH8AIW8BAH8AIQMEAAC-AQAgBgAAvwEAIFUAAI0BACADAAAAQQAgAQAAQgAwAgAAPgAgAwAAAEEAIAEAAEIAMAIAAD4AIAMAAABBACABAABCADACAAA-ACAHBAAAvAEAIAYAAL0BACBUAQAAAAFVAQAAAAFfQAAAAAFuAQAAAAFvAQAAAAEBDgAARgAgBVQBAAAAAVUBAAAAAV9AAAAAAW4BAAAAAW8BAAAAAQEOAABIADABDgAASAAwBwQAAKABACAGAAChAQAgVAEAkwEAIVUBAJQBACFfQACXAQAhbgEAkwEAIW8BAJMBACECAAAAPgAgDgAASwAgBVQBAJMBACFVAQCUAQAhX0AAlwEAIW4BAJMBACFvAQCTAQAhAgAAAEEAIA4AAE0AIAIAAABBACAOAABNACADAAAAPgAgFQAARgAgFgAASwAgAQAAAD4AIAEAAABBACAEBwAAnQEAIBsAAJ8BACAcAACeAQAgVQAAjQEAIAhRAAB9ADBSAABUABBTAAB9ADBUAQBuACFVAQBvACFfQAByACFuAQBuACFvAQBuACEDAAAAQQAgAQAAUwAwGgAAVAAgAwAAAEEAIAEAAEIAMAIAAD4AIAEAAAAKACABAAAACgAgAwAAAAgAIAEAAAkAMAIAAAoAIAMAAAAIACABAAAJADACAAAKACADAAAACAAgAQAACQAwAgAACgAgDgMAAJsBACAFAACcAQAgVAEAAAABVQEAAAABVgEAAAABVwEAAAABWAIAAAABWQEAAAABWgEAAAABWwAAmgEAIFwBAAAAAV0BAAAAAV4BAAAAAV9AAAAAAQEOAABcACAMVAEAAAABVQEAAAABVgEAAAABVwEAAAABWAIAAAABWQEAAAABWgEAAAABWwAAmgEAIFwBAAAAAV0BAAAAAV4BAAAAAV9AAAAAAQEOAABeADABDgAAXgAwDgMAAJgBACAFAACZAQAgVAEAkwEAIVUBAJMBACFWAQCUAQAhVwEAlAEAIVgCAJUBACFZAQCUAQAhWgEAlAEAIVsAAJYBACBcAQCUAQAhXQEAkwEAIV4BAJMBACFfQACXAQAhAgAAAAoAIA4AAGEAIAxUAQCTAQAhVQEAkwEAIVYBAJQBACFXAQCUAQAhWAIAlQEAIVkBAJQBACFaAQCUAQAhWwAAlgEAIFwBAJQBACFdAQCTAQAhXgEAkwEAIV9AAJcBACECAAAACAAgDgAAYwAgAgAAAAgAIA4AAGMAIAMAAAAKACAVAABcACAWAABhACABAAAACgAgAQAAAAgAIAsHAACOAQAgGwAAkQEAIBwAAJABACBNAACPAQAgTgAAkgEAIFYAAI0BACBXAACNAQAgWAAAjQEAIFkAAI0BACBaAACNAQAgXAAAjQEAIA9RAABtADBSAABqABBTAABtADBUAQBuACFVAQBuACFWAQBvACFXAQBvACFYAgBwACFZAQBvACFaAQBvACFbAABxACBcAQBvACFdAQBuACFeAQBuACFfQAByACEDAAAACAAgAQAAaQAwGgAAagAgAwAAAAgAIAEAAAkAMAIAAAoAIA9RAABtADBSAABqABBTAABtADBUAQBuACFVAQBuACFWAQBvACFXAQBvACFYAgBwACFZAQBvACFaAQBvACFbAABxACBcAQBvACFdAQBuACFeAQBuACFfQAByACEOBwAAdAAgGwAAfAAgHAAAfAAgYAEAAAABYQEAAAAEYgEAAAAEYwEAAAABZAEAAAABZQEAAAABZgEAAAABZwEAewAhawEAAAABbAEAAAABbQEAAAABDgcAAHcAIBsAAHoAIBwAAHoAIGABAAAAAWEBAAAABWIBAAAABWMBAAAAAWQBAAAAAWUBAAAAAWYBAAAAAWcBAHkAIWsBAAAAAWwBAAAAAW0BAAAAAQ0HAAB3ACAbAAB3ACAcAAB3ACBNAAB4ACBOAAB3ACBgAgAAAAFhAgAAAAViAgAAAAVjAgAAAAFkAgAAAAFlAgAAAAFmAgAAAAFnAgB2ACEEYAEAAAAFaAEAAAABaQEAAAAEagEAAAAECwcAAHQAIBsAAHUAIBwAAHUAIGBAAAAAAWFAAAAABGJAAAAABGNAAAAAAWRAAAAAAWVAAAAAAWZAAAAAAWdAAHMAIQsHAAB0ACAbAAB1ACAcAAB1ACBgQAAAAAFhQAAAAARiQAAAAARjQAAAAAFkQAAAAAFlQAAAAAFmQAAAAAFnQABzACEIYAIAAAABYQIAAAAEYgIAAAAEYwIAAAABZAIAAAABZQIAAAABZgIAAAABZwIAdAAhCGBAAAAAAWFAAAAABGJAAAAABGNAAAAAAWRAAAAAAWVAAAAAAWZAAAAAAWdAAHUAIQ0HAAB3ACAbAAB3ACAcAAB3ACBNAAB4ACBOAAB3ACBgAgAAAAFhAgAAAAViAgAAAAVjAgAAAAFkAgAAAAFlAgAAAAFmAgAAAAFnAgB2ACEIYAIAAAABYQIAAAAFYgIAAAAFYwIAAAABZAIAAAABZQIAAAABZgIAAAABZwIAdwAhCGAIAAAAAWEIAAAABWIIAAAABWMIAAAAAWQIAAAAAWUIAAAAAWYIAAAAAWcIAHgAIQ4HAAB3ACAbAAB6ACAcAAB6ACBgAQAAAAFhAQAAAAViAQAAAAVjAQAAAAFkAQAAAAFlAQAAAAFmAQAAAAFnAQB5ACFrAQAAAAFsAQAAAAFtAQAAAAELYAEAAAABYQEAAAAFYgEAAAAFYwEAAAABZAEAAAABZQEAAAABZgEAAAABZwEAegAhawEAAAABbAEAAAABbQEAAAABDgcAAHQAIBsAAHwAIBwAAHwAIGABAAAAAWEBAAAABGIBAAAABGMBAAAAAWQBAAAAAWUBAAAAAWYBAAAAAWcBAHsAIWsBAAAAAWwBAAAAAW0BAAAAAQtgAQAAAAFhAQAAAARiAQAAAARjAQAAAAFkAQAAAAFlAQAAAAFmAQAAAAFnAQB8ACFrAQAAAAFsAQAAAAFtAQAAAAEIUQAAfQAwUgAAVAAQUwAAfQAwVAEAbgAhVQEAbwAhX0AAcgAhbgEAbgAhbwEAbgAhCgQAAIIBACAGAACDAQAgUQAAfgAwUgAAQQAQUwAAfgAwVAEAfwAhVQEAgAEAIV9AAIEBACFuAQB_ACFvAQB_ACELYAEAAAABYQEAAAAEYgEAAAAEYwEAAAABZAEAAAABZQEAAAABZgEAAAABZwEAfAAhawEAAAABbAEAAAABbQEAAAABC2ABAAAAAWEBAAAABWIBAAAABWMBAAAAAWQBAAAAAWUBAAAAAWYBAAAAAWcBAHoAIWsBAAAAAWwBAAAAAW0BAAAAAQhgQAAAAAFhQAAAAARiQAAAAARjQAAAAAFkQAAAAAFlQAAAAAFmQAAAAAFnQAB1ACEDcAAAAwAgcQAAAwAgcgAAAwAgA3AAAAgAIHEAAAgAIHIAAAgAIAdRAACEAQAwUgAAOwAQUwAAhAEAMFQBAG4AIV0BAG4AIV4BAG4AIXMBAG4AIQhRAACFAQAwUgAAJQAQUwAAhQEAMFQBAG4AIVUBAG4AIV9AAHIAIXQBAG4AIXUBAG4AIQoGAACDAQAgCAAAggEAIFEAAIYBADBSAAASABBTAACGAQAwVAEAfwAhVQEAfwAhX0AAgQEAIXQBAH8AIXUBAH8AIREDAACJAQAgBQAAigEAIFEAAIcBADBSAAAIABBTAACHAQAwVAEAfwAhVQEAfwAhVgEAgAEAIVcBAIABACFYAgCIAQAhWQEAgAEAIVoBAIABACFbAABxACBcAQCAAQAhXQEAfwAhXgEAfwAhX0AAgQEAIQhgAgAAAAFhAgAAAAViAgAAAAVjAgAAAAFkAgAAAAFlAgAAAAFmAgAAAAFnAgB3ACEMBgAAgwEAIAgAAIIBACBRAACGAQAwUgAAEgAQUwAAhgEAMFQBAH8AIVUBAH8AIV9AAIEBACF0AQB_ACF1AQB_ACF3AAASACB4AAASACAMBAAAggEAIAYAAIMBACBRAAB-ADBSAABBABBTAAB-ADBUAQB_ACFVAQCAAQAhX0AAgQEAIW4BAH8AIW8BAH8AIXcAAEEAIHgAAEEAIAJdAQAAAAFeAQAAAAEJAwAAiQEAIAUAAIoBACBRAACMAQAwUgAAAwAQUwAAjAEAMFQBAH8AIV0BAH8AIV4BAH8AIXMBAH8AIQAAAAAAAAF8AQAAAAEBfAEAAAABBXwCAAAAAYMBAgAAAAGEAQIAAAABhQECAAAAAYYBAgAAAAECfAEAAAAEggEBAAAABQF8QAAAAAEFFQAA8AEAIBYAAPYBACB5AADxAQAgegAA9QEAIH8AAAEAIAUVAADuAQAgFgAA8wEAIHkAAO8BACB6AADyAQAgfwAAPgAgAXwBAAAABAMVAADwAQAgeQAA8QEAIH8AAAEAIAMVAADuAQAgeQAA7wEAIH8AAD4AIAAAAAsVAACuAQAwFgAAswEAMHkAAK8BADB6AACwAQAwewAAsQEAIHwAALIBADB9AACyAQAwfgAAsgEAMH8AALIBADCAAQAAtAEAMIEBAAC1AQAwCxUAAKIBADAWAACnAQAweQAAowEAMHoAAKQBADB7AAClAQAgfAAApgEAMH0AAKYBADB-AACmAQAwfwAApgEAMIABAACoAQAwgQEAAKkBADAMAwAAmwEAIFQBAAAAAVUBAAAAAVYBAAAAAVcBAAAAAVgCAAAAAVkBAAAAAVoBAAAAAVsAAJoBACBcAQAAAAFdAQAAAAFfQAAAAAECAAAACgAgFQAArQEAIAMAAAAKACAVAACtAQAgFgAArAEAIAEOAADtAQAwEQMAAIkBACAFAACKAQAgUQAAhwEAMFIAAAgAEFMAAIcBADBUAQAAAAFVAQB_ACFWAQCAAQAhVwEAgAEAIVgCAIgBACFZAQCAAQAhWgEAgAEAIVsAAHEAIFwBAIABACFdAQB_ACFeAQB_ACFfQACBAQAhAgAAAAoAIA4AAKwBACACAAAAqgEAIA4AAKsBACAPUQAAqQEAMFIAAKoBABBTAACpAQAwVAEAfwAhVQEAfwAhVgEAgAEAIVcBAIABACFYAgCIAQAhWQEAgAEAIVoBAIABACFbAABxACBcAQCAAQAhXQEAfwAhXgEAfwAhX0AAgQEAIQ9RAACpAQAwUgAAqgEAEFMAAKkBADBUAQB_ACFVAQB_ACFWAQCAAQAhVwEAgAEAIVgCAIgBACFZAQCAAQAhWgEAgAEAIVsAAHEAIFwBAIABACFdAQB_ACFeAQB_ACFfQACBAQAhC1QBAJMBACFVAQCTAQAhVgEAlAEAIVcBAJQBACFYAgCVAQAhWQEAlAEAIVoBAJQBACFbAACWAQAgXAEAlAEAIV0BAJMBACFfQACXAQAhDAMAAJgBACBUAQCTAQAhVQEAkwEAIVYBAJQBACFXAQCUAQAhWAIAlQEAIVkBAJQBACFaAQCUAQAhWwAAlgEAIFwBAJQBACFdAQCTAQAhX0AAlwEAIQwDAACbAQAgVAEAAAABVQEAAAABVgEAAAABVwEAAAABWAIAAAABWQEAAAABWgEAAAABWwAAmgEAIFwBAAAAAV0BAAAAAV9AAAAAAQQDAAC7AQAgVAEAAAABXQEAAAABcwEAAAABAgAAAAUAIBUAALoBACADAAAABQAgFQAAugEAIBYAALgBACABDgAA7AEAMAoDAACJAQAgBQAAigEAIFEAAIwBADBSAAADABBTAACMAQAwVAEAAAABXQEAfwAhXgEAfwAhcwEAfwAhdgAAiwEAIAIAAAAFACAOAAC4AQAgAgAAALYBACAOAAC3AQAgB1EAALUBADBSAAC2AQAQUwAAtQEAMFQBAH8AIV0BAH8AIV4BAH8AIXMBAH8AIQdRAAC1AQAwUgAAtgEAEFMAALUBADBUAQB_ACFdAQB_ACFeAQB_ACFzAQB_ACEDVAEAkwEAIV0BAJMBACFzAQCTAQAhBAMAALkBACBUAQCTAQAhXQEAkwEAIXMBAJMBACEFFQAA5wEAIBYAAOoBACB5AADoAQAgegAA6QEAIH8AAAEAIAQDAAC7AQAgVAEAAAABXQEAAAABcwEAAAABAxUAAOcBACB5AADoAQAgfwAAAQAgBBUAAK4BADB5AACvAQAwewAAsQEAIH8AALIBADAEFQAAogEAMHkAAKMBADB7AAClAQAgfwAApgEAMAAAAAAABRUAAOIBACAWAADlAQAgeQAA4wEAIHoAAOQBACB_AAA-ACADFQAA4gEAIHkAAOMBACB_AAA-ACAAAAALFQAA0wEAMBYAANcBADB5AADUAQAwegAA1QEAMHsAANYBACB8AACyAQAwfQAAsgEAMH4AALIBADB_AACyAQAwgAEAANgBADCBAQAAtQEAMAsVAADKAQAwFgAAzgEAMHkAAMsBADB6AADMAQAwewAAzQEAIHwAAKYBADB9AACmAQAwfgAApgEAMH8AAKYBADCAAQAAzwEAMIEBAACpAQAwDAUAAJwBACBUAQAAAAFVAQAAAAFWAQAAAAFXAQAAAAFYAgAAAAFZAQAAAAFaAQAAAAFbAACaAQAgXAEAAAABXgEAAAABX0AAAAABAgAAAAoAIBUAANIBACADAAAACgAgFQAA0gEAIBYAANEBACABDgAA4QEAMAIAAAAKACAOAADRAQAgAgAAAKoBACAOAADQAQAgC1QBAJMBACFVAQCTAQAhVgEAlAEAIVcBAJQBACFYAgCVAQAhWQEAlAEAIVoBAJQBACFbAACWAQAgXAEAlAEAIV4BAJMBACFfQACXAQAhDAUAAJkBACBUAQCTAQAhVQEAkwEAIVYBAJQBACFXAQCUAQAhWAIAlQEAIVkBAJQBACFaAQCUAQAhWwAAlgEAIFwBAJQBACFeAQCTAQAhX0AAlwEAIQwFAACcAQAgVAEAAAABVQEAAAABVgEAAAABVwEAAAABWAIAAAABWQEAAAABWgEAAAABWwAAmgEAIFwBAAAAAV4BAAAAAV9AAAAAAQQFAADEAQAgVAEAAAABXgEAAAABcwEAAAABAgAAAAUAIBUAANsBACADAAAABQAgFQAA2wEAIBYAANoBACABDgAA4AEAMAIAAAAFACAOAADaAQAgAgAAALYBACAOAADZAQAgA1QBAJMBACFeAQCTAQAhcwEAkwEAIQQFAADDAQAgVAEAkwEAIV4BAJMBACFzAQCTAQAhBAUAAMQBACBUAQAAAAFeAQAAAAFzAQAAAAEEFQAA0wEAMHkAANQBADB7AADWAQAgfwAAsgEAMAQVAADKAQAweQAAywEAMHsAAM0BACB_AACmAQAwAgYAAL8BACAIAAC-AQAgAwQAAL4BACAGAAC_AQAgVQAAjQEAIANUAQAAAAFeAQAAAAFzAQAAAAELVAEAAAABVQEAAAABVgEAAAABVwEAAAABWAIAAAABWQEAAAABWgEAAAABWwAAmgEAIFwBAAAAAV4BAAAAAV9AAAAAAQYGAAC9AQAgVAEAAAABVQEAAAABX0AAAAABbgEAAAABbwEAAAABAgAAAD4AIBUAAOIBACADAAAAQQAgFQAA4gEAIBYAAOYBACAIAAAAQQAgBgAAoQEAIA4AAOYBACBUAQCTAQAhVQEAlAEAIV9AAJcBACFuAQCTAQAhbwEAkwEAIQYGAAChAQAgVAEAkwEAIVUBAJQBACFfQACXAQAhbgEAkwEAIW8BAJMBACEGBgAA3QEAIFQBAAAAAVUBAAAAAV9AAAAAAXQBAAAAAXUBAAAAAQIAAAABACAVAADnAQAgAwAAABIAIBUAAOcBACAWAADrAQAgCAAAABIAIAYAAMkBACAOAADrAQAgVAEAkwEAIVUBAJMBACFfQACXAQAhdAEAkwEAIXUBAJMBACEGBgAAyQEAIFQBAJMBACFVAQCTAQAhX0AAlwEAIXQBAJMBACF1AQCTAQAhA1QBAAAAAV0BAAAAAXMBAAAAAQtUAQAAAAFVAQAAAAFWAQAAAAFXAQAAAAFYAgAAAAFZAQAAAAFaAQAAAAFbAACaAQAgXAEAAAABXQEAAAABX0AAAAABBgQAALwBACBUAQAAAAFVAQAAAAFfQAAAAAFuAQAAAAFvAQAAAAECAAAAPgAgFQAA7gEAIAYIAADcAQAgVAEAAAABVQEAAAABX0AAAAABdAEAAAABdQEAAAABAgAAAAEAIBUAAPABACADAAAAQQAgFQAA7gEAIBYAAPQBACAIAAAAQQAgBAAAoAEAIA4AAPQBACBUAQCTAQAhVQEAlAEAIV9AAJcBACFuAQCTAQAhbwEAkwEAIQYEAACgAQAgVAEAkwEAIVUBAJQBACFfQACXAQAhbgEAkwEAIW8BAJMBACEDAAAAEgAgFQAA8AEAIBYAAPcBACAIAAAAEgAgCAAAyAEAIA4AAPcBACBUAQCTAQAhVQEAkwEAIV9AAJcBACF0AQCTAQAhdQEAkwEAIQYIAADIAQAgVAEAkwEAIVUBAJMBACFfQACXAQAhdAEAkwEAIXUBAJMBACEDBg4EBwAGCAYCAgMAAQUAAwMEBwIGCwQHAAUCAwABBQADAgQMAAYNAAIGEAAIDwAAAAADBwALGwAMHAANAAAAAwcACxsADBwADQIDAAEFAAMCAwABBQADAwcAEhsAExwAFAAAAAMHABIbABMcABQAAAMHABkbABocABsAAAADBwAZGwAaHAAbAgMAAQUAAwIDAAEFAAMFBwAgGwAjHAAkTQAhTgAiAAAAAAAFBwAgGwAjHAAkTQAhTgAiCQIBChEBCxQBDBUBDRYBDxgBEBoHERsIEh0BEx8HFCAJFyEBGCIBGSMHHSYKHicOHygCICkCISoCIisCIywCJC4CJTAHJjEPJzMCKDUHKTYQKjcCKzgCLDkHLTwRLj0VLz8DMEADMUMDMkQDM0UDNEcDNUkHNkoWN0wDOE4HOU8XOlADO1EDPFIHPVUYPlYcP1cEQFgEQVkEQloEQ1sERF0ERV8HRmAdR2IESGQHSWUeSmYES2cETGgHT2sfUGwl"
};
async function decodeBase64AsWasm(wasmBase64) {
    const { Buffer } = await __turbopack_context__.A("[externals]/node:buffer [external] (node:buffer, cjs, async loader)");
    const wasmArray = Buffer.from(wasmBase64, 'base64');
    return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
    getRuntime: async ()=>await __turbopack_context__.A("[externals]/@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs [external] (@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs, esm_import, [project]/node_modules/@prisma/client, async loader)"),
    getQueryCompilerWasmModule: async ()=>{
        const { wasm } = await __turbopack_context__.A("[externals]/@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs [external] (@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs, esm_import, [project]/node_modules/@prisma/client, async loader)");
        return await decodeBase64AsWasm(wasm);
    },
    importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
    return __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["getPrismaClient"](config);
}
}),
"[project]/generated/prisma/internal/prismaNamespace.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "AnyNull",
    ()=>AnyNull,
    "DbNull",
    ()=>DbNull,
    "Decimal",
    ()=>Decimal,
    "DocumentScalarFieldEnum",
    ()=>DocumentScalarFieldEnum,
    "JsonNull",
    ()=>JsonNull,
    "ModelName",
    ()=>ModelName,
    "NullTypes",
    ()=>NullTypes,
    "NullsOrder",
    ()=>NullsOrder,
    "OrganizationMemberScalarFieldEnum",
    ()=>OrganizationMemberScalarFieldEnum,
    "OrganizationScalarFieldEnum",
    ()=>OrganizationScalarFieldEnum,
    "PrismaClientInitializationError",
    ()=>PrismaClientInitializationError,
    "PrismaClientKnownRequestError",
    ()=>PrismaClientKnownRequestError,
    "PrismaClientRustPanicError",
    ()=>PrismaClientRustPanicError,
    "PrismaClientUnknownRequestError",
    ()=>PrismaClientUnknownRequestError,
    "PrismaClientValidationError",
    ()=>PrismaClientValidationError,
    "QueryMode",
    ()=>QueryMode,
    "SortOrder",
    ()=>SortOrder,
    "Sql",
    ()=>Sql,
    "TransactionIsolationLevel",
    ()=>TransactionIsolationLevel,
    "UserScalarFieldEnum",
    ()=>UserScalarFieldEnum,
    "defineExtension",
    ()=>defineExtension,
    "empty",
    ()=>empty,
    "getExtensionContext",
    ()=>getExtensionContext,
    "join",
    ()=>join,
    "prismaVersion",
    ()=>prismaVersion,
    "raw",
    ()=>raw,
    "sql",
    ()=>sql
]);
/* !!! This is code generated by Prisma. Do not edit directly. !!! */ /* eslint-disable */ // biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */ var __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__ = __turbopack_context__.i("[externals]/@prisma/client/runtime/client [external] (@prisma/client/runtime/client, cjs, [project]/node_modules/@prisma/client)");
;
const PrismaClientKnownRequestError = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["PrismaClientKnownRequestError"];
const PrismaClientUnknownRequestError = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["PrismaClientUnknownRequestError"];
const PrismaClientRustPanicError = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["PrismaClientRustPanicError"];
const PrismaClientInitializationError = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["PrismaClientInitializationError"];
const PrismaClientValidationError = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["PrismaClientValidationError"];
const sql = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["sqltag"];
const empty = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["empty"];
const join = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["join"];
const raw = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["raw"];
const Sql = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["Sql"];
const Decimal = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["Decimal"];
const getExtensionContext = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["Extensions"].getExtensionContext;
const prismaVersion = {
    client: "7.5.0",
    engine: "280c870be64f457428992c43c1f6d557fab6e29e"
};
const NullTypes = {
    DbNull: __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["NullTypes"].DbNull,
    JsonNull: __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["NullTypes"].JsonNull,
    AnyNull: __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["NullTypes"].AnyNull
};
const DbNull = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["DbNull"];
const JsonNull = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["JsonNull"];
const AnyNull = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["AnyNull"];
const ModelName = {
    Organization: 'Organization',
    OrganizationMember: 'OrganizationMember',
    User: 'User',
    Document: 'Document'
};
const TransactionIsolationLevel = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["makeStrictEnum"]({
    ReadUncommitted: 'ReadUncommitted',
    ReadCommitted: 'ReadCommitted',
    RepeatableRead: 'RepeatableRead',
    Serializable: 'Serializable'
});
const OrganizationScalarFieldEnum = {
    id: 'id',
    clerkOrgId: 'clerkOrgId',
    name: 'name',
    slug: 'slug',
    createdAt: 'createdAt'
};
const OrganizationMemberScalarFieldEnum = {
    id: 'id',
    organizationId: 'organizationId',
    userId: 'userId',
    role: 'role'
};
const UserScalarFieldEnum = {
    id: 'id',
    clerkUserId: 'clerkUserId',
    email: 'email',
    name: 'name',
    createdAt: 'createdAt'
};
const DocumentScalarFieldEnum = {
    id: 'id',
    name: 'name',
    content: 'content',
    fileUrl: 'fileUrl',
    fileSize: 'fileSize',
    fileType: 'fileType',
    aiSummary: 'aiSummary',
    aiKeywords: 'aiKeywords',
    sentiment: 'sentiment',
    organizationId: 'organizationId',
    userId: 'userId',
    createdAt: 'createdAt'
};
const SortOrder = {
    asc: 'asc',
    desc: 'desc'
};
const QueryMode = {
    default: 'default',
    insensitive: 'insensitive'
};
const NullsOrder = {
    first: 'first',
    last: 'last'
};
const defineExtension = __TURBOPACK__imported__module__$5b$externals$5d2f40$prisma$2f$client$2f$runtime$2f$client__$5b$external$5d$__$2840$prisma$2f$client$2f$runtime$2f$client$2c$__cjs$2c$__$5b$project$5d2f$node_modules$2f40$prisma$2f$client$29$__["Extensions"].defineExtension;
}),
"[project]/generated/prisma/client.ts [app-rsc] (ecmascript) <locals>", ((__turbopack_context__) => {
"use strict";

/* !!! This is code generated by Prisma. Do not edit directly. !!! */ /* eslint-disable */ // biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */ __turbopack_context__.s([
    "PrismaClient",
    ()=>PrismaClient
]);
var __TURBOPACK__imported__module__$5b$externals$5d2f$node$3a$path__$5b$external$5d$__$28$node$3a$path$2c$__cjs$29$__ = __turbopack_context__.i("[externals]/node:path [external] (node:path, cjs)");
var __TURBOPACK__imported__module__$5b$externals$5d2f$node$3a$url__$5b$external$5d$__$28$node$3a$url$2c$__cjs$29$__ = __turbopack_context__.i("[externals]/node:url [external] (node:url, cjs)");
var __TURBOPACK__imported__module__$5b$project$5d2f$generated$2f$prisma$2f$internal$2f$class$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/generated/prisma/internal/class.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$generated$2f$prisma$2f$internal$2f$prismaNamespace$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/generated/prisma/internal/prismaNamespace.ts [app-rsc] (ecmascript)");
const __TURBOPACK__import$2e$meta__ = {
    get url () {
        return `file://${__turbopack_context__.P("generated/prisma/client.ts")}`;
    },
    get turbopackHot () {
        return __turbopack_context__.m.hot;
    }
};
;
;
globalThis['__dirname'] = __TURBOPACK__imported__module__$5b$externals$5d2f$node$3a$path__$5b$external$5d$__$28$node$3a$path$2c$__cjs$29$__["dirname"]((0, __TURBOPACK__imported__module__$5b$externals$5d2f$node$3a$url__$5b$external$5d$__$28$node$3a$url$2c$__cjs$29$__["fileURLToPath"])(__TURBOPACK__import$2e$meta__.url));
;
;
;
;
const PrismaClient = __TURBOPACK__imported__module__$5b$project$5d2f$generated$2f$prisma$2f$internal$2f$class$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getPrismaClientClass"]();
;
}),
"[project]/lib/prisma.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

return __turbopack_context__.a(async (__turbopack_handle_async_dependencies__, __turbopack_async_result__) => { try {

__turbopack_context__.s([
    "prisma",
    ()=>prisma
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$dotenv$2f$config$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/dotenv/config.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$prisma$2f$adapter$2d$pg$2f$dist$2f$index$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/@prisma/adapter-pg/dist/index.mjs [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$generated$2f$prisma$2f$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/generated/prisma/client.ts [app-rsc] (ecmascript) <locals>");
var __turbopack_async_dependencies__ = __turbopack_handle_async_dependencies__([
    __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$prisma$2f$adapter$2d$pg$2f$dist$2f$index$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__
]);
[__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$prisma$2f$adapter$2d$pg$2f$dist$2f$index$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__] = __turbopack_async_dependencies__.then ? (await __turbopack_async_dependencies__)() : __turbopack_async_dependencies__;
;
;
;
const connectionString = `${process.env.DATABASE_URL}`;
const adapter = new __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$prisma$2f$adapter$2d$pg$2f$dist$2f$index$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["PrismaPg"]({
    connectionString
});
const prisma = new __TURBOPACK__imported__module__$5b$project$5d2f$generated$2f$prisma$2f$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__["PrismaClient"]({
    adapter
});
;
__turbopack_async_result__();
} catch(e) { __turbopack_async_result__(e); } }, false);}),
"[project]/lib/sync-user.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

return __turbopack_context__.a(async (__turbopack_handle_async_dependencies__, __turbopack_async_result__) => { try {

__turbopack_context__.s([
    "syncUserToDatabase",
    ()=>syncUserToDatabase
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$clerk$2f$nextjs$2f$dist$2f$esm$2f$app$2d$router$2f$server$2f$currentUser$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/@clerk/nextjs/dist/esm/app-router/server/currentUser.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/prisma.ts [app-rsc] (ecmascript)");
var __turbopack_async_dependencies__ = __turbopack_handle_async_dependencies__([
    __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__
]);
[__TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__] = __turbopack_async_dependencies__.then ? (await __turbopack_async_dependencies__)() : __turbopack_async_dependencies__;
;
;
async function syncUserToDatabase() {
    try {
        const clerkUser = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$clerk$2f$nextjs$2f$dist$2f$esm$2f$app$2d$router$2f$server$2f$currentUser$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["currentUser"])();
        if (!clerkUser) {
            return null;
        }
        const email = clerkUser.emailAddresses[0]?.emailAddress || "";
        const name = `${clerkUser.firstName || ""} ${clerkUser.lastName || ""}`.trim();
        // Check if user exists in database
        let dbUser = await __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].user.findUnique({
            where: {
                clerkUserId: clerkUser.id
            }
        });
        if (dbUser) {
            // Update existing user
            dbUser = await __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].user.update({
                where: {
                    id: dbUser.id
                },
                data: {
                    email,
                    name: name || dbUser.name
                }
            });
        } else {
            // Create a new user in database
            dbUser = await __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["prisma"].user.create({
                data: {
                    clerkUserId: clerkUser.id,
                    email,
                    name: name || "User"
                }
            });
            console.log(`New user created: ${email}`);
        }
        return dbUser;
    } catch (error) {
        console.error("Error syncing user from Clerk:", error);
        throw error;
    }
}
__turbopack_async_result__();
} catch(e) { __turbopack_async_result__(e); } }, false);}),
"[project]/app/layout.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

return __turbopack_context__.a(async (__turbopack_handle_async_dependencies__, __turbopack_async_result__) => { try {

__turbopack_context__.s([
    "default",
    ()=>RootLayout,
    "metadata",
    ()=>metadata
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$inter_5972bc34$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[next]/internal/font/google/inter_5972bc34.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$clerk$2f$nextjs$2f$dist$2f$esm$2f$index$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/node_modules/@clerk/nextjs/dist/esm/index.js [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$common$2f$header$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/components/common/header.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$common$2f$site$2d$footer$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/components/common/site-footer.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$sonner$2f$dist$2f$index$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/sonner/dist/index.mjs [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$sync$2d$user$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/sync-user.ts [app-rsc] (ecmascript)");
var __turbopack_async_dependencies__ = __turbopack_handle_async_dependencies__([
    __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$sync$2d$user$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__
]);
[__TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$sync$2d$user$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__] = __turbopack_async_dependencies__.then ? (await __turbopack_async_dependencies__)() : __turbopack_async_dependencies__;
;
;
;
;
;
;
;
;
const metadata = {
    title: "Lumina-HQ | Multi-Tenant Document Intelligence Platform",
    description: "Turn your organization's documents into a searchable, actionable knowledge base with multi-tenant AI analysis."
};
async function RootLayout({ children }) {
    await (0, __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$sync$2d$user$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["syncUserToDatabase"])();
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f40$clerk$2f$nextjs$2f$dist$2f$esm$2f$index$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__["ClerkProvider"], {
        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("html", {
            lang: "en",
            suppressHydrationWarning: true,
            children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("body", {
                className: __TURBOPACK__imported__module__$5b$next$5d2f$internal$2f$font$2f$google$2f$inter_5972bc34$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"].className,
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                    className: "min-h-screen flex flex-col",
                    children: [
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$common$2f$header$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {}, void 0, false, {
                            fileName: "[project]/app/layout.tsx",
                            lineNumber: 28,
                            columnNumber: 13
                        }, this),
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("main", {
                            className: "flex-1",
                            children: children
                        }, void 0, false, {
                            fileName: "[project]/app/layout.tsx",
                            lineNumber: 29,
                            columnNumber: 13
                        }, this),
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$common$2f$site$2d$footer$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {}, void 0, false, {
                            fileName: "[project]/app/layout.tsx",
                            lineNumber: 30,
                            columnNumber: 13
                        }, this),
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$sonner$2f$dist$2f$index$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["Toaster"], {
                            position: "top-right",
                            richColors: true
                        }, void 0, false, {
                            fileName: "[project]/app/layout.tsx",
                            lineNumber: 31,
                            columnNumber: 13
                        }, this)
                    ]
                }, void 0, true, {
                    fileName: "[project]/app/layout.tsx",
                    lineNumber: 27,
                    columnNumber: 11
                }, this)
            }, void 0, false, {
                fileName: "[project]/app/layout.tsx",
                lineNumber: 26,
                columnNumber: 9
            }, this)
        }, void 0, false, {
            fileName: "[project]/app/layout.tsx",
            lineNumber: 25,
            columnNumber: 7
        }, this)
    }, void 0, false, {
        fileName: "[project]/app/layout.tsx",
        lineNumber: 24,
        columnNumber: 5
    }, this);
}
__turbopack_async_result__();
} catch(e) { __turbopack_async_result__(e); } }, false);}),
"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/layout.tsx [app-rsc] (ecmascript)"));
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__0o7vtks._.js.map